AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  EchoRequest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://xxxxxxxxx/e382216c65415f264826a88ea7ef1885
      Description: ''
      MemorySize: 512
      Timeout: 63
      Role: arn:aws:iam::xxxxxxxx:role/lambda_basic_execution
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET
Outputs:
  ApiURL:
    Description: API Gateway endpoint URL for Prod stage for API Gateway Multi-Origin
      CORS function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
